### ISSUE TITLE
error with windows7 (32 and 64bit) and QGIS 2.2

### ISSUE THREAD

**Issue by ghtmtt** [faunalia/rt_qspider#1]
Problem with Windows machines. 
When using the plugin, there appears this message:

An error has occured while executing Python code:
Traceback (most recent call last):
  File "C:\Users\matteo.qgis-custom/python/plugins\rt_qspider\dialog.py", line 136, in accept
    print x2d_toconv, y2d_toconv
IOError: [Errno 9] Bad file descriptor

Python version:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

QGIS version:
2.2.0-Valmiera Valmiera, c3a2817

Python path: ['C:/PROGRA~1/QGISMA~1/apps/qgis/./python/plugins\processing', 'C:/PROGRA~1/QGISMA~1/apps/qgis/./python', u'C:\Users\matteo\.qgis-custom/python', u'C:\Users\matteo\.qgis-custom/python/plugins', 'C:/PROGRA~1/QGISMA~1/apps/qgis/./python/plugins', 'C:\PROGRA~1\QGISMA~1\bin\python27.zip', 'C:\PROGRA~1\QGISMA~1\apps\Python27\DLLs', 'C:\PROGRA~1\QGISMA~1\apps\Python27\lib', 'C:\PROGRA~1\QGISMA~1\apps\Python27\lib\plat-win', 'C:\PROGRA~1\QGISMA~1\apps\Python27\lib\lib-tk', 'C:\PROGRA~1\QGISMA~1\bin', 'C:\PROGRA~1\QGISMA~1\apps\Python27', 'C:\PROGRA~1\QGISMA~1\apps\Python27\lib\site-packages', 'C:\PROGRA~1\QGISMA~1\apps\Python27\lib\site-packages\GDAL-1.11.0-py2.7-win32.egg', 'C:\PROGRA~1\QGISMA~1\apps\Python27\lib\site-packages\PIL', 'C:\PROGRA~1\QGISMA~1\apps\Python27\lib\site-packages\win32', 'C:\PROGRA~1\QGISMA~1\apps\Python27\lib\site-packages\win32\lib', 'C:\PROGRA~1\QGISMA~1\apps\Python27\lib\site-packages\Pythonwin', 'C:\PROGRA~1\QGISMA~1\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win32.egg', 'C:\PROGRA~1\QGISMA~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode', 'C:\PROGRA~1\QGISMA~1\apps\qgis\python\plugins\fTools\tools']

no problem with the same data on Debian (testing) with QGIS 2.3

**Comment by luipir** [comment]
why it was closed? what was the solution?

**Comment by pcav** [comment]
Wrong tracker
